### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by HR1991** [michz/shinage-server#45]
in presentation image links are broken for ex: pool/emailaddress / ..... .jpg so this structure doesnt work 
also after add image in presentation you cant delete presentation and get error

**Comment by michz** [comment]
Hi @HR1991 ,
thank you for reporting these issues.

Could you please tell me which version you are using? (Released Tag or latest master or specific commit?)

As all releases are pre-v1 versions there is still a lot of change in handling of files, paths and uploads.
I'm still not satisfied how file handling is implemented right now, so this will probably have changed in current master compared to latest "released" version and will probably change in future.

I will have a look at these problems in near future.

**Comment by HR1991** [comment]
Np michz
Latest Version

**Comment by michz** [comment]
Long time ago…

Should be fixed in current master. I am able to upload files and select them in the presentation. Thumbnails work, adding them work, removing them works for me now.

Closing here. If you are still motivated ( :wink: ) and think that there is still a problem feel free to re-open.
