### ISSUE TITLE
Composer dependencies require a PHP version ">= 8.0.2"

### ISSUE THREAD

**Issue by thanhtantran** [michz/shinage-server#91]
I have PHP 7.4 and in readme it said requires only PHP 7.4

but when i ran `php bin/console doctrine:schema:update --force`

It returns 

_Composer detected issues in your platform:_

_Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.30._

_PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.30. in /home/ubuntu/shinage-server/vendor/composer/platform_check.php on line 24_

**Comment by michz** [comment]
Thanks for reporting! Indeed, I forgot to adjust the README. Will be fixed in #93
